### ISSUE TITLE
Is the service loading JSON schemas when running on Windows?

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/oneview-redfish-toolkit#197]
As oneview-redfish-toolkit user, I should be able to run the service with local JSON schema validation enabled for all resources available.

**Comment by ffdarkpenguin** [comment]
The following error happens when accessing /redfish/v1 on windows machine

2018-01-16 02:19:44,749 - werkzeug - INFO - 127.0.0.1 - - [16/Jan/2018 02:19:44] "GET /redfish/v1/ HTTP/1.1" 500 -
2018-01-16 02:26:22,230 - root - ERROR - ServiceRoot error: ServiceRoot.v1_2_0.json not found
Traceback (most recent call last):
  File "c:\users\ff\projeto\oneview-redfish-toolkit\oneview_redfish_toolkit\api\redfish_json_validator.py", line 74, in _validate
    "http://redfish.dmtf.org/schemas/v1/" + schema_version]
KeyError: 'http://redfish.dmtf.org/schemas/v1/ServiceRoot.v1_2_0.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ff\projeto\oneview-redfish-toolkit\oneview_redfish_toolkit\blueprints\service_root.py", line 47, in get_service_root
    sr = ServiceRoot(uuid)
  File "c:\users\ff\projeto\oneview-redfish-toolkit\oneview_redfish_toolkit\api\service_root.py", line 69, in __init__
    self._validate()
  File "c:\users\ff\projeto\oneview-redfish-toolkit\oneview_redfish_toolkit\api\redfish_json_validator.py", line 76, in _validate
    raise OneViewRedfishError("{} not found".format(schema_version))
oneview_redfish_toolkit.api.errors.OneViewRedfishError: ServiceRoot.v1_2_0.json not found
2018-01-16 02:26:22,232 - werkzeug - INFO - 127.0.0.1 - - [16/Jan/2018 02:26:22] "GET /redfish/v1/ HTTP/1.1" 500 -
